package com.iwas.task.enums;

public enum TaskActivityType {
    TASK_CREATED,
    STATUS_CHANGED,
    PRIORITY_CHANGED,
    ASSIGNEE_CHANGED,
    ESTIMATE_CHANGED,
    TYPE_CHANGED,
    TITLE_CHANGED,
    DESCRIPTION_CHANGED,
    START_DATE_CHANGED,
    DUE_DATE_CHANGED,
    ATTACHMENT_ADDED,
    ATTACHMENT_REMOVED,
    TASK_DELETED
}
