spring:
  application:
    name: Workforce
  datasource:
    url: jdbc:postgresql://localhost:5432/workforce
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
  mail:
    username: toilaatmin@gmail.com
    password: laijaybhzvszxfdz
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 9090

app:
  mail:
    from: toilaatmin@gmail.com
  rabbitmq:
    email-queue: email.verification
  frontend:
    base-url: http://localhost:5173
  jwt:
    secret: hs5p8JHcpEdoZeiE5uRIDCev4rMczXRP
    access-expiration-ms: 900000
    refresh-expiration-ms: 604800000
    expiration: 86400000