spring.application.name=Roamtrip
server.port=9090

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Flyway (tu? ch?nh n?u c?n)
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

#jwt configuration
app.jwt.secret=hs5p8JHcpEdoZeiE5uRIDCev4rMczXRP
app.jwt.access-expiration-ms=900000
app.jwt.refresh-expiration-ms=604800000

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
app.rabbitmq.email-queue=email.verification

# Mail
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
app.mail.from=no-reply@roamtrip.local

# Frontend
app.frontend.base-url=http://localhost:5173
